//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int RowId { get; set; }
        public int ProjectId { get; set; }
        public string CommentText { get; set; }
        public string Commentor { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string StepName { get; set; }
    }
}
