//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Steps
    {
        public int RowId { get; set; }
        public int ProjectId { get; set; }
        public string StepName { get; set; }
        public Nullable<System.DateTime> StartDateEstimated { get; set; }
        public Nullable<System.DateTime> StartDateActual { get; set; }
        public Nullable<System.DateTime> EndDateEstimated { get; set; }
        public Nullable<System.DateTime> EndDateActual { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Status { get; set; }
    }
}
