//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public int StepId { get; set; }
        public string StepName { get; set; }
        public int SequenceNo { get; set; }
        public int CreatorId { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    }
}
